# Generated by Django 4.1.7 on 2023-03-05 09:01

import digital_dex_admin_web.models.admin_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('td_no', models.IntegerField()),
                ('property_choices', models.CharField(choices=[('L', 'Land'), ('B', 'Building'), ('M', 'Machinery'), ('O', 'Others')], max_length=1, null=True)),
                ('taxable', models.CharField(choices=[('T', 'Taxable'), ('E', 'Exempt')], max_length=1, null=True)),
                ('date_assessed', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tax Declaration of Real Property',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=digital_dex_admin_web.models.admin_model.upload_profile_location)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('phone_num', models.CharField(max_length=11, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=digital_dex_admin_web.models.admin_model.upload_signature_location)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin account',
                'verbose_name_plural': 'Admin account',
            },
        ),
    ]
