# Generated by Django 4.1.7 on 2023-04-05 12:36

import digital_dex_admin_web.models.admin_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialAssessment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=255, null=True)),
                ('area', models.FloatField(null=True)),
                ('market_value', models.FloatField(null=True)),
                ('actual_use', models.CharField(max_length=255, null=True)),
                ('assessment_level', models.FloatField(null=True)),
                ('assessed_value', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Initial Assessment',
                'verbose_name_plural': 'Initial Assessment',
            },
        ),
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('td_no', models.CharField(max_length=255, null=True)),
                ('property_identification_no', models.IntegerField(null=True)),
                ('owner', models.CharField(max_length=255, null=True)),
                ('owner_tin', models.IntegerField(null=True)),
                ('owner_address', models.CharField(max_length=255, null=True)),
                ('owner_tel_no', models.CharField(max_length=255, null=True)),
                ('administrator_beneficial_user', models.CharField(max_length=255, null=True)),
                ('admin_tin', models.IntegerField(null=True)),
                ('admin_address', models.CharField(max_length=255, null=True)),
                ('admin_tel_no', models.CharField(max_length=255, null=True)),
                ('property_location', models.CharField(max_length=255, null=True)),
                ('oct_no', models.IntegerField(null=True)),
                ('survey_no', models.IntegerField(null=True)),
                ('cct', models.CharField(max_length=255, null=True)),
                ('lot_no', models.IntegerField(null=True)),
                ('dated', models.DateField(max_length=255, null=True)),
                ('blk_no', models.IntegerField(null=True)),
                ('north', models.FloatField(max_length=255, null=True)),
                ('west', models.FloatField(max_length=255, null=True)),
                ('east', models.FloatField(max_length=255, null=True)),
                ('south', models.FloatField(max_length=255, null=True)),
                ('property_choices', models.CharField(choices=[('L', 'Land'), ('B', 'Building'), ('M', 'Machinery'), ('O', 'Others')], max_length=1, null=True)),
                ('mach_brief_description', models.TextField(max_length=255, null=True)),
                ('no_of_storeys', models.IntegerField(null=True)),
                ('brief_description', models.TextField(max_length=255, null=True)),
                ('specify', models.TextField(max_length=255, null=True)),
                ('total_assessed_value_words', models.CharField(max_length=255, null=True)),
                ('total_assessed_value', models.FloatField(null=True)),
                ('total_market_value', models.FloatField(null=True)),
                ('taxable', models.CharField(choices=[('T', 'Taxable'), ('E', 'Exempt')], max_length=1, null=True)),
                ('qtr', models.IntegerField(null=True)),
                ('year', models.DateField(max_length=255, null=True)),
                ('approved_by', models.CharField(max_length=255, null=True)),
                ('date_assessed', models.DateField()),
                ('cancels_td_no', models.CharField(max_length=255, null=True)),
                ('cancel_owner', models.CharField(max_length=255, null=True)),
                ('cancel_previous_av_pph', models.CharField(max_length=255, null=True)),
                ('memoranda', models.TextField(max_length=255, null=True)),
                ('date_modified', models.DateField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status_choices', models.CharField(choices=[('R', 'Recently Updated'), ('P', 'Processing')], max_length=1, null=True)),
                ('initial_assessments', models.ManyToManyField(to='digital_dex_admin_web.initialassessment')),
            ],
            options={
                'verbose_name': 'Tax Declaration of Real Property',
                'verbose_name_plural': 'Tax Declaration of Real Properties',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=digital_dex_admin_web.models.admin_model.upload_profile_location)),
                ('full_name', models.CharField(max_length=255, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('phone_num', models.CharField(max_length=11, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to=digital_dex_admin_web.models.admin_model.upload_signature_location)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin account',
                'verbose_name_plural': 'Admin account',
            },
        ),
    ]
