# Generated by Django 4.1.7 on 2023-03-05 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digital_dex_admin_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxform',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digital_dex_admin_web.admin'),
        ),
    ]
